// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home/ElectricityOverview","parentId":"@@/global-layout","id":"1"},"2":{"path":"/home","parentId":"@@/global-layout","id":"2"},"3":{"path":"/home/ElectricityOverview","parentId":"2","id":"3"},"4":{"path":"/home/ElectricityAnalysis","parentId":"2","id":"4"},"5":{"path":"/home/ElectricityPerformance","parentId":"2","id":"5"},"6":{"path":"/home/ExpandOverview","parentId":"2","id":"6"},"7":{"path":"/home/ExpandAnalysis","parentId":"2","id":"7"},"8":{"path":"/home/ExpandPerformance","parentId":"2","id":"8"},"9":{"path":"/control","parentId":"@@/global-layout","id":"9"},"10":{"path":"/doubleColumnar/:name","parentId":"@@/global-layout","id":"10"},"11":{"path":"/economyIndex/:name","parentId":"@@/global-layout","id":"11"},"12":{"path":"/comparisonModal","parentId":"@@/global-layout","id":"12"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__ElectricityOverview__index" */'@/pages/Home/ElectricityOverview/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Home__ElectricityAnalysis__index" */'@/pages/Home/ElectricityAnalysis/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Home__ElectricityPerformance__index" */'@/pages/Home/ElectricityPerformance/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Home__ExpandOverview__index" */'@/pages/Home/ExpandOverview/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Home__ExpandAnalysis__index" */'@/pages/Home/ExpandAnalysis/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Home__ExpandPerformance__index" */'@/pages/Home/ExpandPerformance/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__ControlPage__index" */'@/pages/ControlPage/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__DoubleColumnar__index" */'@/pages/DoubleColumnar/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__EconomyIndex__index" */'@/pages/EconomyIndex/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__ComparisonModal__index" */'@/pages/ComparisonModal/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'C:/台州能源/_web/src/layouts/index.tsx')),
},
  };
}
